import { h } from '../../h.js';
import { useSeoHead } from '../../components/SeoHead.js';

function SectionDivider() {
  return h('hr', { style: { border: 'none', borderTop: '1px solid #dee2e6', margin: '32px 0' } });
}

function DictTable(props: { rows: Array<[string, string, string]> }) {
  return h('table', {
    style: {
      width: '100%',
      borderCollapse: 'collapse',
      fontSize: '0.9rem',
      marginBottom: '20px',
    },
  },
    h('thead', null,
      h('tr', null,
        h('th', { style: { textAlign: 'left', padding: '8px 12px', borderBottom: '2px solid #dee2e6', fontWeight: '600', color: '#1d3557' } }, 'Column'),
        h('th', { style: { textAlign: 'left', padding: '8px 12px', borderBottom: '2px solid #dee2e6', fontWeight: '600', color: '#1d3557' } }, 'Unit'),
        h('th', { style: { textAlign: 'left', padding: '8px 12px', borderBottom: '2px solid #dee2e6', fontWeight: '600', color: '#1d3557' } }, 'Description'),
      ),
    ),
    h('tbody', null,
      ...props.rows.map(([col, unit, desc], i) =>
        h('tr', {
          key: String(i),
          style: { background: i % 2 === 0 ? '#f8f9fa' : '#fff' },
        },
          h('td', { style: { padding: '6px 12px', borderBottom: '1px solid #e9ecef' } }, h('code', null, col)),
          h('td', { style: { padding: '6px 12px', borderBottom: '1px solid #e9ecef', color: '#6c757d' } }, unit),
          h('td', { style: { padding: '6px 12px', borderBottom: '1px solid #e9ecef', color: '#495057' } }, desc),
        )
      ),
    ),
  );
}

const proseStyle = { color: '#495057', maxWidth: '72ch', lineHeight: '1.6', fontSize: '0.98rem' };

export function EconomyAbout() {
  useSeoHead(
    'Data & Citations',
    'Data dictionary, provenance, and source attribution for the US economy analysis covering 1999 to present.',
  );

  return h('div', null,
    h('h1', null, 'Data & Citations'),
    h('p', { style: { color: '#6c757d', fontSize: '0.95rem' } },
      'Dictionary, provenance, and source attribution',
    ),

    // About this analysis
    h('h2', null, 'About this analysis'),
    h('p', { style: proseStyle },
      'A static, open-source interactive look at the US economy covering 1999 to present, comparing the current year against every completed year in the window. Every chart is an interactive JavaScript widget rendered into a self-contained HTML page.',
    ),

    h('h3', null, 'Data sourcing at a glance'),
    h('ul', { style: { ...proseStyle, lineHeight: '2' } },
      h('li', null,
        h('strong', null, 'Macro series'),
        ' (GDP, employment, inflation, Fed Funds, 10Y Treasury, NBER recession, GDP components) are ',
        h('strong', null, 'live FRED data'),
        ' \u2014 fetched daily by a GitHub Action using the public FRED API, incrementally cached under ',
        h('code', null, 'data/economy/cache/'),
        ', and committed back to the repo. These are all US government public-domain series.',
      ),
      h('li', null,
        h('strong', null, 'Market series'),
        ' (S&P 500, Dow, NASDAQ, VIX, sector returns) are a ',
        h('strong', null, 'calibrated synthetic overlay'),
        '. FRED\'s licenses on these proprietary series explicitly prohibit redistribution, so no raw third-party data is stored in or served from this site.',
      ),
      h('li', null,
        h('strong', null, 'The current (partial) year'),
        ' is flagged with an asterisk (',
        h('code', null, '*'),
        ') in charts and tables. In the CSV, ',
        h('code', null, 'prototype = 1'),
        ' marks the current year.',
      ),
    ),

    h(SectionDivider, null),

    // Data dictionary
    h('h2', null, 'Data dictionary'),

    // annual.csv
    h('h3', null, h('code', null, 'annual.csv'), ' \u2014 1999 to current year, one row per calendar year'),
    h(DictTable, {
      rows: [
        ['year', 'integer', 'Calendar year (1999 to current year)'],
        ['gdp_growth', '%', 'Real GDP growth, year-over-year (proxy for BEA series GDPC1)'],
        ['unemployment', '%', 'Civilian unemployment rate, annual average (BLS LNS14000000)'],
        ['cpi', '%', 'CPI-U inflation, year-over-year (BLS CUUR0000SA0)'],
        ['fed_funds', '%', 'Federal Funds target rate, end-of-period (Federal Reserve)'],
        ['ten_year', '%', '10-year Treasury constant-maturity yield, annual average (US Treasury)'],
        ['sp500_ret', '%', 'S&P 500 annual total return'],
        ['dow_ret', '%', 'Dow Jones Industrial Average annual price return'],
        ['nasdaq_ret', '%', 'NASDAQ Composite annual price return'],
        ['vix_avg', 'index level', 'CBOE Volatility Index (VIX), annual mean of daily close'],
        ['recession', '0 / 1', 'NBER recession indicator \u2014 1 if any part of the year was a recession'],
        ['deficit_pct_gdp', '%', 'Federal surplus (+) or deficit (\u2212) as % of GDP, fiscal-year basis (FRED FYFSGDA188S)'],
        ['debt_pct_gdp_eoy', '%', 'Federal public debt as % of GDP, year-end Q4 value (FRED GFDEGDQ188S)'],
        ['debt_trillion_eoy', 'trillions of $', 'Federal public debt at year-end (FRED GFDEBTN, Q4 value / 1e6)'],
        ['debt_added_trillion', 'trillions of $', 'Debt added this calendar year = debt_trillion_eoy minus prior year\'s debt_trillion_eoy'],
        ['prototype', '0 / 1', '1 = current (partial) year; 0 = completed year'],
      ],
    }),

    // quarterly.csv
    h('h3', null, h('code', null, 'quarterly.csv'), ' \u2014 1999Q1 through most recent available quarter'),
    h(DictTable, {
      rows: [
        ['year, quarter', 'integer', 'Year and quarter (1\u20134)'],
        ['date', 'ISO date', 'First day of the quarter'],
        ['period', 'label', 'YYYYQn (e.g., 2023Q4)'],
        ['gdp_growth', '%', 'Quarterly real GDP growth (YoY proxy)'],
        ['unemployment', '%', 'Quarterly average unemployment rate'],
        ['cpi', '%', 'Quarterly CPI YoY'],
        ['fed_funds', '%', 'Quarterly average Federal Funds rate'],
        ['ten_year', '%', 'Quarterly average 10Y Treasury yield'],
        ['sp500_ret_qoq', '%', 'S&P 500 quarter-over-quarter return'],
        ['vix', 'index level', 'Quarterly average VIX'],
      ],
    }),

    // monthly.csv
    h('h3', null, h('code', null, 'monthly.csv'), ' \u2014 1999-01 through most recent month'),
    h(DictTable, {
      rows: [
        ['year, month', 'integer', 'Year and month (1\u201312)'],
        ['date', 'ISO date', 'First day of the month'],
        ['unemployment', '%', 'Monthly unemployment rate'],
        ['cpi', '%', 'Monthly CPI YoY'],
        ['fed_funds', '%', 'Monthly Federal Funds rate'],
        ['ten_year', '%', 'Monthly 10Y Treasury yield'],
        ['vix', 'index level', 'Monthly average VIX'],
        ['sp500_level', 'index level', 'S&P 500 month-end level'],
      ],
    }),

    // gdp_components.csv
    h('h3', null, h('code', null, 'gdp_components.csv'), ' \u2014 expenditure shares'),
    h(DictTable, {
      rows: [
        ['year', 'integer', 'Calendar year'],
        ['consumption', '% of GDP', 'Personal Consumption Expenditures (C)'],
        ['investment', '% of GDP', 'Gross Private Domestic Investment (I)'],
        ['government', '% of GDP', 'Government Consumption + Investment (G)'],
        ['net_exports', '% of GDP', 'Net Exports of Goods & Services (NX)'],
      ],
    }),
    h('p', { style: { ...proseStyle, fontSize: '0.9rem', color: '#6c757d' } },
      'Shares sum to ~100 by construction.',
    ),

    // fiscal_quarterly.csv
    h('h3', null, h('code', null, 'fiscal_quarterly.csv'), ' \u2014 federal debt, quarterly'),
    h(DictTable, {
      rows: [
        ['year, quarter', 'integer', 'Year and quarter (1\u20134)'],
        ['date', 'ISO date', 'First day of the quarter'],
        ['debt_trillion', 'trillions of $', 'Total public federal debt outstanding (FRED GFDEBTN, millions $ / 1e6)'],
        ['debt_pct_gdp', '%', 'Federal public debt as % of GDP (FRED GFDEGDQ188S)'],
      ],
    }),

    // sectors.csv
    h('h3', null, h('code', null, 'sectors.csv'), ' \u2014 S&P 500 GICS sector returns'),
    h(DictTable, {
      rows: [
        ['year', 'integer', 'Calendar year'],
        ['sector', 'text', 'GICS Level-1 sector (e.g., Information Technology, Financials)'],
        ['return_pct', '%', 'Annual total return for the sector'],
      ],
    }),

    h(SectionDivider, null),

    // Data provenance
    h('h2', null, 'Data provenance'),
    h('p', { style: proseStyle },
      h('strong', null, 'Macro series (2000 \u2013 present)'),
      ' \u2014 live values from FRED, refreshed daily by a scheduled GitHub Action. Each series is cached to ',
      h('code', null, 'data/economy/cache/{key}.csv'),
      ' and only new observations (since the last cached date) are requested on subsequent runs. FRED release revisions propagate on the next refresh.',
    ),
    h('p', { style: proseStyle },
      h('strong', null, 'Current (partial) year'),
      ' \u2014 the row for the current calendar year contains only the portion of the year that FRED has released so far; it is marked ',
      h('code', null, 'prototype = 1'),
      ' and shown with an asterisk (',
      h('code', null, '*'),
      '). Treat it as provisional.',
    ),
    h('p', { style: proseStyle },
      h('strong', null, 'Market series (all years)'),
      ' \u2014 ',
      h('code', null, 'sp500_ret'),
      ', ',
      h('code', null, 'dow_ret'),
      ', ',
      h('code', null, 'nasdaq_ret'),
      ', ',
      h('code', null, 'vix_avg'),
      ' (and the derived ',
      h('code', null, 'sp500_level'),
      ', ',
      h('code', null, 'vix'),
      ', ',
      h('code', null, 'sp500_ret_qoq'),
      ', and sector returns) are synthetic. FRED hosts these indices but licenses them from S&P DJI, Nasdaq, and Cboe with a no-redistribution clause. Storing them in this public repository would violate those licenses, so synthetic values calibrated to the historical shape are used instead. Correlations and drill-downs involving market series are therefore ',
      h('em', null, 'illustrative of what the dashboard could show with a licensed data feed'),
      ', not reproductions of actual index performance.',
    ),
    h('p', { style: proseStyle },
      h('strong', null, 'Sector returns'),
      ' \u2014 derived from synthetic S&P 500 returns via published historical sector betas plus noise.',
    ),

    h(SectionDivider, null),

    // Citations
    h('h2', null, 'Citations'),

    h('h3', null, 'Public-domain US government data'),
    h('p', { style: proseStyle },
      'US government works are in the public domain under 17 U.S.C. \u00A7 105 and may be freely reused.',
    ),
    h('ol', { style: { ...proseStyle, lineHeight: '2' } },
      h('li', null,
        h('strong', null, 'U.S. Bureau of Economic Analysis.'),
        ' ',
        h('em', null, 'Real Gross Domestic Product'),
        ' [GDPC1]. Retrieved from Federal Reserve Bank of St. Louis, FRED. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/GDPC1', target: '_blank', rel: 'noopener noreferrer' }, 'https://fred.stlouisfed.org/series/GDPC1'),
      ),
      h('li', null,
        h('strong', null, 'U.S. Bureau of Economic Analysis.'),
        ' ',
        h('em', null, 'National Income and Product Accounts Tables \u2014 Gross Domestic Product: Components.'),
        ' ',
        h('a', { href: 'https://www.bea.gov/data/gdp/gross-domestic-product', target: '_blank', rel: 'noopener noreferrer' }, 'https://www.bea.gov/data/gdp/gross-domestic-product'),
      ),
      h('li', null,
        h('strong', null, 'U.S. Bureau of Labor Statistics.'),
        ' ',
        h('em', null, 'Civilian Unemployment Rate'),
        ' [UNRATE / LNS14000000]. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/UNRATE', target: '_blank', rel: 'noopener noreferrer' }, 'https://fred.stlouisfed.org/series/UNRATE'),
      ),
      h('li', null,
        h('strong', null, 'U.S. Bureau of Labor Statistics.'),
        ' ',
        h('em', null, 'Consumer Price Index for All Urban Consumers: All Items in U.S. City Average'),
        ' [CPIAUCSL / CUUR0000SA0]. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/CPIAUCSL', target: '_blank', rel: 'noopener noreferrer' }, 'https://fred.stlouisfed.org/series/CPIAUCSL'),
      ),
      h('li', null,
        h('strong', null, 'Board of Governors of the Federal Reserve System (US).'),
        ' ',
        h('em', null, 'Federal Funds Effective Rate'),
        ' [FEDFUNDS]. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/FEDFUNDS', target: '_blank', rel: 'noopener noreferrer' }, 'https://fred.stlouisfed.org/series/FEDFUNDS'),
      ),
      h('li', null,
        h('strong', null, 'Board of Governors of the Federal Reserve System (US).'),
        ' ',
        h('em', null, 'Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis'),
        ' [DGS10]. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/DGS10', target: '_blank', rel: 'noopener noreferrer' }, 'https://fred.stlouisfed.org/series/DGS10'),
      ),
      h('li', null,
        h('strong', null, 'National Bureau of Economic Research.'),
        ' ',
        h('em', null, 'US Business Cycle Expansions and Contractions'),
        ' (recession dating). ',
        h('a', { href: 'https://www.nber.org/research/data/us-business-cycle-expansions-and-contractions', target: '_blank', rel: 'noopener noreferrer' }, 'https://www.nber.org/research/data/us-business-cycle-expansions-and-contractions'),
      ),
      h('li', null,
        h('strong', null, 'U.S. Department of the Treasury. Fiscal Service.'),
        ' ',
        h('em', null, 'Federal Surplus or Deficit'),
        ' [FYFSD], ',
        h('em', null, 'Federal Surplus or Deficit as Percent of GDP'),
        ' [FYFSGDA188S]. Public-domain fiscal data. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/FYFSD', target: '_blank', rel: 'noopener noreferrer' }, 'FYFSD'),
        ', ',
        h('a', { href: 'https://fred.stlouisfed.org/series/FYFSGDA188S', target: '_blank', rel: 'noopener noreferrer' }, 'FYFSGDA188S'),
      ),
      h('li', null,
        h('strong', null, 'U.S. Department of the Treasury. Fiscal Service.'),
        ' ',
        h('em', null, 'Federal Debt: Total Public Debt'),
        ' [GFDEBTN], ',
        h('em', null, 'Federal Debt: Total Public Debt as Percent of Gross Domestic Product'),
        ' [GFDEGDQ188S]. Public-domain. ',
        h('a', { href: 'https://fred.stlouisfed.org/series/GFDEBTN', target: '_blank', rel: 'noopener noreferrer' }, 'GFDEBTN'),
        ', ',
        h('a', { href: 'https://fred.stlouisfed.org/series/GFDEGDQ188S', target: '_blank', rel: 'noopener noreferrer' }, 'GFDEGDQ188S'),
      ),
    ),

    h('h3', null, 'Proprietary third-party data \u2014 attribution only, not redistributed'),
    h('p', { style: proseStyle },
      'The series below are referenced for analytical context. Their index names are trademarks of the respective owners and are used nominatively; no affiliation or endorsement is implied. This analysis ',
      h('strong', null, 'does not redistribute the underlying proprietary series'),
      ' \u2014 historical values are synthesized from public commentary and the current dataset is the calibrated prototype.',
    ),
    h('ol', { start: '10', style: { ...proseStyle, lineHeight: '2' } },
      h('li', null,
        h('strong', null, 'S&P Dow Jones Indices LLC.'),
        ' ',
        h('em', null, 'S&P 500 Index.'),
        ' "S&P" and "S&P 500" are registered trademarks of Standard & Poor\'s Financial Services LLC, a division of S&P Global. ',
        h('a', { href: 'https://www.spglobal.com/spdji/', target: '_blank', rel: 'noopener noreferrer' }, 'https://www.spglobal.com/spdji/'),
      ),
      h('li', null,
        h('strong', null, 'S&P Dow Jones Indices LLC / Dow Jones & Company, Inc.'),
        ' ',
        h('em', null, 'Dow Jones Industrial Average.'),
        ' "Dow Jones" and "DJIA" are trademarks of S&P Dow Jones Indices LLC and/or Dow Jones & Company, Inc.',
      ),
      h('li', null,
        h('strong', null, 'Nasdaq, Inc.'),
        ' ',
        h('em', null, 'NASDAQ Composite Index.'),
        ' "NASDAQ" is a registered trademark of Nasdaq, Inc. ',
        h('a', { href: 'https://www.nasdaq.com/', target: '_blank', rel: 'noopener noreferrer' }, 'https://www.nasdaq.com/'),
      ),
      h('li', null,
        h('strong', null, 'Cboe Global Markets, Inc.'),
        ' ',
        h('em', null, 'Cboe Volatility Index (VIX).'),
        ' "VIX" and "Cboe" are registered trademarks of Cboe Global Markets, Inc. ',
        h('a', { href: 'https://www.cboe.com/tradable_products/vix/', target: '_blank', rel: 'noopener noreferrer' }, 'https://www.cboe.com/tradable_products/vix/'),
      ),
      h('li', null,
        h('strong', null, 'Global Industry Classification Standard (GICS)'),
        ' \u2014 sector taxonomy is jointly owned by MSCI Inc. and S&P Global. Sector names used here follow GICS Level 1. ',
        h('a', { href: 'https://www.msci.com/our-solutions/indexes/gics', target: '_blank', rel: 'noopener noreferrer' }, 'https://www.msci.com/our-solutions/indexes/gics'),
      ),
    ),

    h('h3', null, 'FRED terms of use'),
    h('p', { style: proseStyle },
      'Where FRED is cited as the retrieval endpoint, the FRED Terms of Use apply: public-domain series are unrestricted; proprietary licensed series may not be redistributed without the data owner\'s permission. See ',
      h('a', { href: 'https://fred.stlouisfed.org/legal/#copyright', target: '_blank', rel: 'noopener noreferrer' }, 'https://fred.stlouisfed.org/legal/#copyright'),
      '.',
    ),

    h(SectionDivider, null),

    // Open-source stack
    h('h2', null, 'Open-source stack'),
    h('table', {
      style: {
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: '0.9rem',
        marginBottom: '20px',
      },
    },
      h('thead', null,
        h('tr', null,
          h('th', { style: { textAlign: 'left', padding: '8px 12px', borderBottom: '2px solid #dee2e6', fontWeight: '600', color: '#1d3557' } }, 'Component'),
          h('th', { style: { textAlign: 'left', padding: '8px 12px', borderBottom: '2px solid #dee2e6', fontWeight: '600', color: '#1d3557' } }, 'Role'),
          h('th', { style: { textAlign: 'left', padding: '8px 12px', borderBottom: '2px solid #dee2e6', fontWeight: '600', color: '#1d3557' } }, 'License'),
        ),
      ),
      h('tbody', null,
        ...[
          ['Quarto', 'Authoring + site generator', 'MIT'],
          ['Apache ECharts via echarts4r', 'Drill-down charts (sunburst, treemap, bars, lines, heatmap)', 'Apache 2.0'],
          ['Plotly.js via plotly (R)', 'Scatter / linked charts', 'MIT'],
          ['reactable', 'Interactive tables', 'MIT'],
          ['jQuery Sparkline via sparkline (R)', 'Inline mini-charts', 'BSD-3'],
          ['crosstalk', 'Client-side linked filtering', 'MIT'],
          ['Bootstrap (via Quarto\'s cosmo theme)', 'Page layout & typography', 'MIT'],
        ].map(([comp, role, lic], i) =>
          h('tr', {
            key: String(i),
            style: { background: i % 2 === 0 ? '#f8f9fa' : '#fff' },
          },
            h('td', { style: { padding: '6px 12px', borderBottom: '1px solid #e9ecef' } }, comp),
            h('td', { style: { padding: '6px 12px', borderBottom: '1px solid #e9ecef', color: '#495057' } }, role),
            h('td', { style: { padding: '6px 12px', borderBottom: '1px solid #e9ecef', color: '#6c757d' } }, lic),
          )
        ),
      ),
    ),

    // Code license
    h('h2', null, 'Code license'),
    h('p', { style: proseStyle },
      'The source code for this site is released under the MIT License. See the ',
      h('a', { href: 'https://github.com/sam-caldwell/samcaldwell.info/blob/main/LICENSE', target: '_blank', rel: 'noopener noreferrer' }, 'LICENSE'),
      ' file in the repository for the full text.',
    ),

    h(SectionDivider, null),

    // Disclaimer
    h('h2', null, 'Disclaimer'),
    h('p', { style: proseStyle },
      'Nothing in this analysis constitutes investment, tax, legal, or financial advice. The dataset is a calibrated synthetic prototype provided for illustration of the visualization stack; it should not be used as a source of record for any economic, trading, or reporting decision.',
    ),
  );
}
